#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd com.cdsoftware.docuware.targetplatform
./plugin-builder $DEBUG_MODE ../com.cdsoftware.docuware ../com.cdsoftware.docuware.test
